create database Final_pro1;
use Final_pro1;

create database final_pro1;
use final_pro1;
select * from order_items;

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    brand_id INT NOT NULL,
    category_id INT NOT NULL,
    model_year INT NOT NULL,
    list_price DECIMAL(10,2) NOT NULL
);

-- 1. Inner Join for Order Details  
-- Join orders, order_items, and products to display detailed line items. 

SELECT
    o.order_id,
    o.order_date,
    oi.item_id,
    p.product_name,
    oi.quantity,
    oi.list_price,
    oi.discount
FROM orders o
INNER JOIN order_items oi
ON o.order_id = oi.order_id
INNER JOIN products p
ON oi.product_id = p.product_id;

-- 2. Total Sales by Store  
-- Write a query to group sales (total_price) by each store_id.

SELECT
    o.store_id,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_sales
FROM orders o
INNER JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY o.store_id;

-- 3. Top 5 Selling Products  
-- Use ORDER BY and LIMIT to get the top 5 most sold products by  quantity.  

SELECT
    p.product_name,
    SUM(oi.quantity) AS total_quantity
FROM order_items oi
INNER JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC
LIMIT 5;

-- 4. Purchase Summary  
-- For each customer, return total orders placed, total items purchased,  and total revenue.  

SELECT
    c.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity) AS total_items,
    SUM(oi.quantity * oi.list_price * (1-oi.discount)) AS total_revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_id, customer_name;

-- 5. Segment Customers by Total Spend  
-- Write a query to classify customers into spending brackets (e.g., low,  medium, high).  

SELECT
    c.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    SUM(oi.quantity * oi.list_price * (1-oi.discount)) AS total_spend,

CASE
WHEN SUM(oi.quantity * oi.list_price * (1-oi.discount)) < 1000
THEN 'Low'

WHEN SUM(oi.quantity * oi.list_price * (1-oi.discount))
BETWEEN 1000 AND 5000
THEN 'Medium'

ELSE 'High'
END AS spending_segment

FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id

JOIN order_items oi
ON o.order_id=oi.order_id

GROUP BY c.customer_id, customer_name;

-- 6. Staff Performance Analysis  
-- Analyze total revenue generated by each staff member based on their  handled orders. 

SELECT
    s.staff_id,
    CONCAT(s.first_name,' ',s.last_name) AS staff_name,
    SUM(oi.quantity * oi.list_price * (1-oi.discount)) AS total_revenue
FROM staffs s
JOIN orders o
ON s.staff_id=o.staff_id
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY s.staff_id, staff_name
ORDER BY total_revenue DESC;

-- 7. Stock Alert Query  
-- Write a query to list products where stock quantity < 10 in any store.

SELECT
    st.store_name,
    p.product_name,
    s.quantity
FROM stocks s
JOIN stores st
ON s.store_id=st.store_id
JOIN products p
ON s.product_id=p.product_id
WHERE s.quantity < 10;

-- 8. Create Final Segmentation Table  done using SQL